import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../../supabase';

// VAPID public key - this should match the one in your edge function
const VAPID_PUBLIC_KEY = 'BPoGue4ZnE769fjfk4zYLjEOn-DilGTk_cfk7qBxaRdXIogBsLNy3-NIOUGOryxL52gG6lENYaYNCyIatc6csgg';

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - base64String.length % 4) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export function usePushNotifications(userId: string | null) {
  const [isSupported, setIsSupported] = useState(false);
  const [isEnabled, setIsEnabled] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [permission, setPermission] = useState<NotificationPermission>('default');

  // Check if push notifications are supported
  useEffect(() => {
    const supported = 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window;
    setIsSupported(supported);
    if (supported) {
      setPermission(Notification.permission);
    }
    setIsLoading(false);
  }, []);

  // Check if user already has a subscription
  useEffect(() => {
    if (!userId || !isSupported) return;

    const checkSubscription = async () => {
      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await registration.pushManager.getSubscription();
        
        if (subscription) {
          // Verify subscription exists in database
          const { data } = await supabase
            .from('push_subscriptions')
            .select('id')
            .eq('user_id', userId)
            .eq('endpoint', subscription.endpoint)
            .single();
          
          setIsEnabled(!!data);
        } else {
          setIsEnabled(false);
        }
      } catch (error) {
        console.error('Error checking push subscription:', error);
        setIsEnabled(false);
      }
    };

    checkSubscription();
  }, [userId, isSupported]);

  const enablePushNotifications = useCallback(async () => {
    if (!userId || !isSupported) return false;
    
    setIsLoading(true);
    
    try {
      // Request permission
      const permissionResult = await Notification.requestPermission();
      setPermission(permissionResult);
      
      if (permissionResult !== 'granted') {
        console.log('Notification permission denied');
        setIsLoading(false);
        return false;
      }

      // Use the main PWA service worker (generated by VitePWA with push handler)
      await navigator.serviceWorker.ready;
      let registration = await navigator.serviceWorker.getRegistration();
      
      if (!registration) {
        console.error('[Push] No service worker registration found');
        setIsLoading(false);
        return false;
      }

      // Unsubscribe from any existing subscription first (to handle VAPID key changes)
      const existingSubscription = await registration.pushManager.getSubscription();
      if (existingSubscription) {
        await existingSubscription.unsubscribe();
        // Delete old subscription from database
        await supabase
          .from('push_subscriptions')
          .delete()
          .eq('user_id', userId);
      }

      // Subscribe to push with new VAPID key
      const applicationServerKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: applicationServerKey as BufferSource
      });

      const subscriptionJSON = subscription.toJSON();
      
      // Delete any old subscriptions for this user first, then insert new one
      await supabase
        .from('push_subscriptions')
        .delete()
        .eq('user_id', userId);
      
      const { error } = await supabase
        .from('push_subscriptions')
        .insert({
          user_id: userId,
          endpoint: subscriptionJSON.endpoint!,
          p256dh: subscriptionJSON.keys!.p256dh,
          auth: subscriptionJSON.keys!.auth
        });

      if (error) {
        console.error('Error saving push subscription:', error);
        setIsLoading(false);
        return false;
      }

      console.log('[Push] Subscription enabled successfully');
      setIsEnabled(true);
      setIsLoading(false);
      return true;
    } catch (error) {
      console.error('Error enabling push notifications:', error);
      setIsLoading(false);
      return false;
    }
  }, [userId, isSupported]);

  const disablePushNotifications = useCallback(async () => {
    if (!userId || !isSupported) return false;
    
    setIsLoading(true);
    
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      
      if (subscription) {
        // Unsubscribe from push
        await subscription.unsubscribe();
        
        // Remove from database
        await supabase
          .from('push_subscriptions')
          .delete()
          .eq('user_id', userId)
          .eq('endpoint', subscription.endpoint);
      }

      setIsEnabled(false);
      setIsLoading(false);
      return true;
    } catch (error) {
      console.error('Error disabling push notifications:', error);
      setIsLoading(false);
      return false;
    }
  }, [userId, isSupported]);

  const togglePushNotifications = useCallback(async () => {
    if (isEnabled) {
      return disablePushNotifications();
    } else {
      return enablePushNotifications();
    }
  }, [isEnabled, enablePushNotifications, disablePushNotifications]);

  return {
    isSupported,
    isEnabled,
    isLoading,
    permission,
    enablePushNotifications,
    disablePushNotifications,
    togglePushNotifications
  };
}
